#os:
#  - linux
dist: bionic

before_install:
  - sudo apt-get update
  - sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
  - curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
